Repository opdev/opcap, pull requests merged in 2022-12, with the labels that each got.

#317 Reorganize and format report templates and JSON
  internal/report/report.go
  internal/report/report_operand_templates.go
  internal/report/report_operator_templates.go
Labels: lgtm, approved, size/M

#320 update go version to 1.19.2 for github CI pipeline
  .github/workflows/build-main.yml
Labels: lgtm, approved, size/XS

#323 update golang version for CItest workflow
  .github/workflows/ciTest.yml
Labels: approved, size/XS

#328 FIX fields order on list bundles
  cmd/list_bundles.go
Labels: lgtm, approved, bug fix, size/XS

#336 Add function to delete CSV before deleting the namespace
  internal/capability/operator_cleanup.go
  internal/operator/client.go
  internal/operator/csv.go
  internal/operator/csv_test.go
Labels: lgtm, approved, size/M
