Repository opdev/opcap, pull requests merged in 2022-11, with the labels that each got.

#295 Add test coverage to the cmd package
  cmd/check.go
  cmd/check_test.go
  cmd/cmd_suite_test.go
  cmd/upload.go
  cmd/upload_test.go
  go.mod
  go.sum
  internal/capability/audit.go
Labels: lgtm, approved, size/L

#309 Remove client requirement from list command
  cmd/list.go
  cmd/list_packages.go
  cmd/list_packages_test.go
  cmd/list_test.go
Labels: lgtm, approved, size/L

#316 Add newline after each json report object
  internal/report/report.go
Labels: lgtm, approved, size/XS

#305 Refactor auditor to use functional options
  cmd/check.go
  internal/capability/audit.go
  internal/capability/auditor.go
  internal/capability/auditor_test.go
  internal/capability/operand_cleanup.go
  internal/capability/operand_install.go
  internal/capability/operator_cleanup.go
  internal/capability/operator_install.go
  internal/capability/suite_test.go
  internal/capability/types.go
Labels: lgtm, approved, size/XL

#310 List bundles
  cmd/list.go
  cmd/list_bundles.go
  cmd/list_bundles_test.go
  cmd/list_packages.go
  go.mod
  go.sum
  internal/bundle/bundle.go
  internal/bundle/bundle_test.go
  internal/bundle/suite_test.go
  internal/bundle/testdata/operators/acc-operator/21.10.19/manifests/acc-operator-controller-manager-metrics-service_v1_service.yaml
  internal/bundle/testdata/operators/acc-operator/21.10.19/manifests/acc-operator-manager-config_v1_configmap.yaml
  internal/bundle/testdata/operators/acc-operator/21.10.19/manifests/acc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
  internal/bundle/testdata/operators/acc-operator/21.10.19/manifests/acc-operator.clusterserviceversion.yaml
  internal/bundle/testdata/operators/acc-operator/21.10.19/manifests/astra.netapp.io_astracontrolcenters.yaml
  internal/bundle/testdata/operators/acc-operator/21.10.19/metadata/annotations.yaml
  internal/bundle/testdata/operators/acc-operator/21.10.7/manifests/acc-operator-controller-manager-metrics-service_v1_service.yaml
  internal/bundle/testdata/operators/acc-operator/21.10.7/manifests/acc-operator-manager-config_v1_configmap.yaml
  internal/bundle/testdata/operators/acc-operator/21.10.7/manifests/acc-operator-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
  internal/bundle/testdata/operators/acc-operator/21.10.7/manifests/acc-operator-manager-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  internal/bundle/testdata/operators/acc-operator/21.10.7/manifests/acc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
  internal/bundle/testdata/operators/acc-operator/21.10.7/manifests/acc-operator.clusterserviceversion.yaml
  internal/bundle/testdata/operators/acc-operator/21.10.7/manifests/astra.netapp.io_astracontrolcenters.yaml
  internal/bundle/testdata/operators/acc-operator/21.10.7/metadata/annotations.yaml
  internal/bundle/testdata/operators/acc-operator/21.12.60/manifests/acc-operator-controller-manager-metrics-service_v1_service.yaml
  internal/bundle/testdata/operators/acc-operator/21.12.60/manifests/acc-operator-manager-config_v1_configmap.yaml
  internal/bundle/testdata/operators/acc-operator/21.12.60/manifests/acc-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
  internal/bundle/testdata/operators/acc-operator/21.12.60/manifests/acc-operator.clusterserviceversion.yaml
  internal/bundle/testdata/operators/acc-operator/21.12.60/manifests/astra.netapp.io_astracontrolcenters.yaml
  internal/bundle/testdata/operators/acc-operator/21.12.60/metadata/annotations.yaml
  internal/bundle/types.go
Labels: lgtm, approved, size/XXL
