Repository opdev/opcap, pull requests merged in 2022-07, with the labels that each got.

#86 Handle empty packagemanifests
  cmd/check.go
Labels: lgtm, approved

#87 Delete outdated README.md
  README.md
Labels: lgtm, approved

#85 Add trace flag to opcap upload
  cmd/upload.go
Labels: lgtm, approved

#81 running gofumpt on the code
  cmd/root.go
  cmd/upload.go
  internal/capability/operator_install.go
  internal/logger/zap.go
  internal/operator/client.go
  internal/operator/csv.go
  internal/operator/install_plan.go
  internal/operator/subscription.go
  internal/operator/version.go
Labels: lgtm, approved

#89 removing .DS_Store file from repo
  internal/.DS_Store
Labels: lgtm, approved

#92 remove creation and deletion of secret functions
  internal/operator/client.go
  internal/operator/secret.go
Labels: lgtm, approved

#91 Updating README for refactored opcap tool
  README.md
Labels: documentation, lgtm, approved

#90 Merge PackageServerClient into OpCapClient
  cmd/check.go
  cmd/root.go
  internal/capability/operator_install.go
  internal/operator/client.go
  internal/operator/namespace.go
  internal/operator/subscription.go
Labels: lgtm, approved

#98 Improve functionality on Operator Install to allow for new features
  cmd/check.go
  internal/capability/audit.go
  internal/capability/auditor.go
  internal/capability/operator_cleanup.go
  internal/capability/operator_install.go
  internal/operator/client.go
  internal/operator/install_plan.go
Labels: lgtm, approved

#107 Add --list-packages flag
  cmd/check.go
Labels: lgtm, approved

#112 CSV bug fixes
  internal/operator/csv.go
Labels: bug, lgtm, approved

#119 Add version command
  Makefile
  cmd/version.go
Labels: lgtm, approved

#115 Add filter flag
  cmd/check.go
  internal/capability/auditor.go
  internal/operator/client.go
  internal/operator/subscription.go
Labels: lgtm, approved

#124 Change module name to github.com/opdev/opcap
  Makefile
  cmd/check.go
  cmd/root.go
  go.mod
  internal/capability/audit.go
  internal/capability/auditor.go
  internal/capability/operator_cleanup.go
  internal/capability/operator_install.go
  internal/operator/client.go
  main.go
Labels: lgtm, approved

#113 Consolidate installPlan functions
  internal/capability/operator_install.go
  internal/operator/client.go
  internal/operator/install_plan.go
  internal/operator/subscription.go
Labels: lgtm, approved

#126 Move client for upload to upload.go
  cmd/root.go
  cmd/upload.go
Labels: lgtm, approved
