Repository opdev/opcap, pull requests merged in 2022-09, with the labels that each got.

#188 Refactor decouple
  cmd/check.go
  internal/capability/audit.go
  internal/capability/auditor.go
  internal/capability/operand_cleanup.go
  internal/capability/operand_install.go
  internal/capability/operator_cleanup.go
  internal/capability/operator_install.go
  internal/capability/report.go
  internal/operator/client.go
  internal/operator/subscription.go
Labels: lgtm, approved, size/XL

#191 Adding Pull Request template
  .github/pull_request_template.md
Labels: documentation, lgtm, approved

#183 Add additional output to --list-packages
  cmd/check.go
Labels: lgtm, approved, size/XS

#180 Adding a GH Action for testing a pull request
  .github/workflows/ciTest.yml
Labels: lgtm, approved, size/M

#178 add test for the check filtered results function
  internal/operator/subscription_test.go
Labels: lgtm, approved, size/S

#193 BUGFIX REMOVE code that breaks at compile time
  internal/operator/subscription_test.go
Labels: lgtm, approved, size/S

#195 Add sample prow config
  .prow.yaml
Labels: lgtm, approved, size/S

#199 Create uploadPreRunE and uploadRunE
  cmd/upload.go
Labels: lgtm, approved, size/L

#204 Remove redundant text from check cmd description
  cmd/check.go
Labels: lgtm, approved, size/S

#196 Support all-installmodes tests for an operator
  cmd/check.go
  internal/capability/auditor.go
  internal/operator/subscription.go
Labels: lgtm, approved, size/M

#194 Remove redundant lines in subscription.go
  internal/operator/subscription.go
Labels: lgtm, approved, size/XS

#208 Pass the same context throughout the stack
  cmd/check.go
  cmd/root.go
  cmd/upload.go
  internal/capability/audit.go
  internal/capability/auditor.go
  internal/capability/operand_cleanup.go
  internal/capability/operand_install.go
  internal/capability/operator_cleanup.go
  internal/capability/operator_install.go
  internal/operator/client.go
  internal/operator/csv.go
  internal/operator/subscription.go
  internal/operator/version.go
Labels: lgtm, approved, size/M

#206 ioutil is deprecated
  cmd/upload.go
Labels: lgtm, approved, size/XS

#211 Update README.md with coveralls
  README.md
Labels: lgtm, approved, size/XS

#221 Fix panic introduced by context param
  internal/capability/auditor.go
Labels: lgtm, approved, size/XS

#222 Fix typos in the documentation
  README.md
  docs/contribution.md
Labels: lgtm, approved, size/XS

#177 Added log package
  cmd/check.go
  cmd/upload.go
  go.mod
  go.sum
  internal/capability/audit.go
  internal/capability/auditor.go
  internal/capability/operand_cleanup.go
  internal/capability/operand_install.go
  internal/capability/operator_cleanup.go
  internal/capability/operator_install.go
  internal/logger/logger.go
  internal/logger/zap.go
  internal/operator/client.go
  internal/operator/csv.go
  internal/operator/namespace.go
  internal/operator/operator_group.go
  internal/operator/subscription.go
Labels: lgtm, approved, size/XL

#205 Update version command to be testable
  cmd/cmd_suite_test.go
  cmd/root.go
  cmd/version.go
  cmd/version_test.go
  go.mod
  go.sum
Labels: lgtm, approved, size/L

#238 Update OWNERS
  OWNERS
Labels: lgtm, approved, size/XS

#240 replace cobra generated description with opcap
  cmd/root.go
Labels: lgtm, approved, size/S

#236 Do not log errors except at the highest level
  internal/capability/audit.go
  internal/capability/auditor.go
  internal/capability/operand_cleanup.go
  internal/capability/operand_install.go
  internal/capability/operator_cleanup.go
  internal/capability/operator_install.go
  internal/operator/client.go
  internal/operator/csv.go
  internal/operator/namespace.go
  internal/operator/namespace_test.go
  internal/operator/operator_group.go
  internal/operator/subscription.go
Labels: lgtm, approved, size/M

#242 add unit tests for operator_group
  internal/operator/operator_group_test.go
Labels: lgtm, approved, size/M

#244 refactor unit tests for namespace and operatorGroup
  internal/operator/namespace_test.go
  internal/operator/operator_group_test.go
Labels: lgtm, approved, size/M

#232 Refactor audits to remove reflection
  internal/capability/audit.go
  internal/capability/auditor.go
  internal/capability/operand_cleanup.go
  internal/capability/operand_install.go
  internal/capability/operator_cleanup.go
  internal/capability/operator_install.go
  internal/capability/report.go
Labels: lgtm, approved, size/XL

#245 refactor unit tests for namespace and operator group
  internal/operator/namespace.go
  internal/operator/namespace_test.go
  internal/operator/operator_group_test.go
Labels: lgtm, approved, size/M

#249 Move reports to use templates
  internal/capability/operand_install.go
  internal/capability/operator_install.go
  internal/capability/report.go
  internal/capability/report_test.go
  internal/capability/suite_test.go
Labels: lgtm, approved, size/L

#250 Fix the log message that were saying "Ignored key"
  internal/logger/logger.go
  internal/logger/logger_test.go
  internal/logger/suite_test.go
  internal/operator/namespace_test.go
  internal/operator/operator_group_test.go
  internal/operator/operator_suite_test.go
Labels: lgtm, approved, size/L
