Repository opdev/opcap, pull requests merged in 2022-08, with the labels that each got.

#109 install ALM_Example from CSV to accomplish OperandInstall and OperandCleanUp
  internal/capability/audit.go
  internal/capability/operand_cleanup.go
  internal/capability/operand_install.go
  internal/operator/client.go
  internal/operator/subscription.go
Labels: lgtm, approved

#123 Reporting package with CSV failure reasons and pretty print to CLI
  .gitignore
  internal/capability/operand_install.go
  internal/capability/operator_install.go
  internal/operator/client.go
  internal/operator/csv.go
  internal/report/report.go
Labels: lgtm, approved

#129 Fixes #110, added description to check command and remaining flags
  cmd/check.go
Labels: lgtm, approved

#139 Update auditplan flag to accept comma separated values
  cmd/check.go
Labels: lgtm, approved

#136 Report improvements and stdout.json replacement
  cmd/upload.go
  internal/capability/audit.go
  internal/capability/auditor.go
  internal/capability/operand_cleanup.go
  internal/capability/operand_install.go
  internal/capability/operator_cleanup.go
  internal/capability/operator_install.go
  internal/capability/report.go
  internal/report/report.go
Labels: lgtm, approved

#148 Fix SIGSEGV from non initialized variable
  cmd/check.go
  internal/operator/csv.go
Labels: lgtm, approved, bug fix

#150 Fix index out of range for operand
  internal/capability/operand_install.go
Labels: lgtm, approved, bug fix

#140 Upload check for Succeeded, failed, or timeout
  cmd/upload.go
Labels: lgtm, approved

#149 update reporting package with operand report
  internal/capability/audit.go
  internal/capability/operand_install.go
  internal/capability/report.go
Labels: lgtm, approved

#154 Added LICENSE file
  LICENSE
Labels: lgtm, approved

#153 Operand status
  cmd/check.go
  cmd/root.go
  cmd/upload.go
  internal/capability/audit.go
  internal/capability/operand_install.go
  internal/capability/operator_install.go
  internal/capability/report.go
  main.go
Labels: enhancement, lgtm, approved

#156 fixed spelling and added missing article
  README.md
Labels: approved

#162 Improve README file
  README.md
  docs/design.md
  docs/maturity.md
Labels: documentation, lgtm, approved

#163 install/report all ALM_Exaples present in a provided CSV
  internal/capability/operand_cleanup.go
  internal/capability/operand_install.go
  internal/capability/report.go
Labels: lgtm, approved

#169 add github issue templates for bug report and new feature request
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom_issue.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: lgtm, approved

#170 fix package manifest filtering feature in ListPackageManifests() method
  cmd/check.go
  internal/operator/client.go
  internal/operator/subscription.go
  internal/operator/subscription_test.go
Labels: lgtm, approved

#171 Update documentation with contribution guidelines
  README.md
  docs/contribution.md
Labels: documentation, lgtm, approved

#173 Add validation for --filter-packages
  cmd/check.go
  internal/operator/subscription.go
Labels: lgtm, approved, size/S

#175 Revert "Add validation for --filter-packages"
  cmd/check.go
  internal/operator/subscription.go
Labels: lgtm, approved, size/S

#176 Revert "Revert "Add validation for --filter-packages""
  cmd/check.go
  internal/operator/subscription.go
Labels: approved, size/S

#174 support testing all install modes supported by an operator
  cmd/check.go
  internal/capability/audit.go
  internal/capability/auditor.go
  internal/operator/client.go
  internal/operator/subscription.go
Labels: lgtm, approved, size/L
