Repository opdev/opcap, pull requests merged in 2022-10, with the labels that each got.

#246 Allow users to provide additional Custom Resources
  cmd/check.go
  internal/capability/audit.go
  internal/capability/auditor.go
  internal/capability/operand_install.go
Labels: lgtm, approved, size/L

#260 Add mgoerens to reviewers list
  OWNERS
Labels: lgtm, approved, size/XS

#253 Allow all operands to be tried on error
  internal/capability/operand_install.go
  internal/logger/logger.go
Labels: lgtm, approved, size/M

#256 Remove remaining list package code from the check command
  cmd/check.go
Labels: lgtm, approved, size/M

#257 Refactor client creation to test CSV operations
  cmd/check.go
  cmd/root.go
  cmd/upload.go
  go.mod
  go.sum
  internal/capability/auditor.go
  internal/capability/operand_cleanup.go
  internal/capability/operand_install.go
  internal/capability/operator_install.go
  internal/operator/client.go
  internal/operator/csv.go
  internal/operator/csv_test.go
  internal/operator/olm.go
  internal/operator/unstructured.go
  internal/operator/version.go
Labels: lgtm, approved, size/L

#269 Fix CSVList for the right operator
  internal/capability/operand_install.go
Labels: lgtm, approved, size/XS

#276 Add a FakeOpClient
  internal/operator/client_fake_test.go
Labels: lgtm, approved, size/S

#272 Truncate namespace when generated
  internal/capability/audit.go
  internal/capability/audit_test.go
Labels: lgtm, approved, size/M

#261 Add support for canceling work upon Ctrl-C
  cmd/root.go
  go.mod
  internal/capability/audit.go
  internal/capability/auditor.go
  internal/capability/operand_cleanup.go
  internal/capability/operand_install.go
  internal/capability/operator_cleanup.go
  internal/capability/operator_install.go
  internal/capability/types.go
  internal/capability/types_test.go
  main.go
Labels: lgtm, approved, size/L

#275 Remove unneeded client code
  go.mod
  internal/capability/operand_cleanup.go
  internal/capability/operand_install.go
  internal/operator/client.go
  internal/operator/csv.go
  internal/operator/csv_test.go
  internal/operator/olm.go
  internal/operator/unstructured.go
Labels: lgtm, approved, size/L

#290 Add check on package name size before cutting slice
  internal/capability/audit.go
Labels: lgtm, approved, size/S

#289 Remove code that was masking errors and panics by running
  main.go
Labels: lgtm, approved, size/XS

#227 Maturity docs
  README.md
  docs/img/opcap-level1.png
  docs/img/opcap-level2.png
  docs/img/opcap-level3.png
  docs/img/opcap-level4.png
  docs/img/opcap-level5.png
  docs/maturity.md
  docs/proposals/maturity.md
Labels: lgtm, size/L

#292 get latest version instead of looping through history
  internal/capability/audit_test.go
  internal/operator/version.go
  internal/operator/version_test.go
Labels: lgtm, approved, size/M

#296 Remove resources as the audits are done
  internal/capability/auditor.go
Labels: lgtm, approved, size/XS

#301 Refactor the 'package list' command to 'list packages'
  cmd/list.go
  cmd/list_packages.go
  cmd/list_packages_test.go
  cmd/list_test.go
  cmd/root.go
Labels: lgtm, approved, size/S

#302 Add an option to pass an afero filesystem to audits
  cmd/check.go
  go.mod
  go.sum
  internal/capability/audit.go
  internal/capability/auditor.go
  internal/capability/operand_install.go
  internal/capability/operator_install.go
  internal/capability/types.go
Labels: lgtm, approved, size/S

#294 internal report package
  internal/capability/audit.go
  internal/capability/operand_cleanup.go
  internal/capability/operand_install.go
  internal/capability/operator_cleanup.go
  internal/capability/operator_install.go
  internal/capability/types.go
  internal/report/report.go
  internal/report/report_test.go
Labels: lgtm, approved, size/L

#303 Add an option to pass an io.Writer to audits
  cmd/check.go
  internal/capability/audit.go
  internal/capability/auditor.go
  internal/capability/operand_install.go
  internal/capability/operator_install.go
  internal/capability/types.go
Labels: lgtm, approved, size/S
