Repository opdev/opcap, pull requests merged in 2023-01, with the labels that each got.

#319 Added test data for list bundles cmd
  cmd/list_bundles.go
  cmd/list_bundles_test.go
Labels: lgtm, approved, size/S

#326 Update go-git to go-git/go-git/v5
  go.mod
  go.sum
  internal/bundle/bundle.go
Labels: lgtm, approved, size/S

#334 ADD report on timed out and failed operators
  .gitignore
  internal/capability/audit.go
  internal/capability/debug.go
  internal/capability/operator_install.go
  internal/capability/types.go
  internal/operator/csv.go
  internal/operator/csv_test.go
  internal/report/report.go
  internal/report/report_debug_operator_templates.go
Labels: lgtm, approved, size/L

#342 ADD check to force finalizer deletion
  .gitignore
  internal/capability/operand_cleanup.go
Labels: lgtm, approved, size/S

#344 Update the finalizers on the server side
  internal/capability/operand_cleanup.go
  internal/operator/client.go
  internal/operator/unstructured.go
Labels: lgtm, approved, size/M

#349 FIX cleanup issues
  internal/capability/operator_cleanup.go
  internal/capability/operator_install.go
Labels: lgtm, approved, size/S
